### ISSUE TITLE
Design fixes 

### ISSUE THREAD

**Issue by pwgryglak** [mirumee/saleor-storefront#119]
Overall:
1. [x] - Change size of saloer logo to 75%  of what it is now.
1. [x] - Gray background to product boxes on listing should be added - color: #F1F5F5
1. [ ] - Filters are not working for me #123
1. [ ] - Load more buttons aren't showing how many products will be shown after loading #85 
1. [ ] - Sign up button doesn't show sign up drawer after click #120
1. [x] - Change font colors from #949494 to #7D7D7D

Desktop: 
1. [x] - Headers for Search, My Bag, My account and Home drawers aren't the same height as navbar -probs my bad
1. [x] - Search should display the box where quick search products should be shown
1. [x] - No Header in Menu Drawer + No close icon
1. [x] - Breadcrumbs should have a hover effect
1. [x] - Increase spacing between categories in nav bar

Mobile:
1. [x] - Search close isn't working on mobile
1. [ ] - On mobile long tap on element in menu drawer - shows hover, doesn't link - can be problematic for users.
1. [ ] - tap on sort by opens up keyboard and allows to type in text - please check how it should behave on Storefront UI Guide - "BEHAVIOUR OF DROPDOWNS MOBILE" #124 
1. [ ] - behaviour of other dropdowns as above #124  

Typography:
1. [x] - h3 line-height: 1.7rem
1. [x] - p line-height: 1.5 rem
